# Generated by Django 3.2.16 on 2023-02-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
