# Generated by Django 3.2.16 on 2023-02-21 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cartitem_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('Food', 'Food'), ('Tools', 'Tools'), ('Toys', 'Toys'), ('Weapons', 'Weapons')], default='none', max_length=200),
        ),
    ]
